- name: Find and Replace
  uses: jacobtomlinson/gha-find-replace@2.0.0
  
  name: Deploy
  on:
    push:
      tags:
        - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "console\.log\(([^)]+)\)"
          replace: ""
          regex: true

      # deployment steps
