import { Fragment } from 'react';

import { MantineSize, Paper, Text, useMantineTheme } from "@mantine/core";
import Head from 'next/head';



function PrivacyPolicy () {

    const theme = useMantineTheme();

    const $violet6 = theme.colors.violet[6];

    const fontSizeIncrementor = (size:MantineSize, incIdx:number) => theme.fontSizes[size] * incIdx as any;



    return (
        <Fragment>

            <Head>
                <title>{process.env.WEBSITE_DOMAIN_NAME} | Privacy Policy</title>
                <meta name="description" content={`${process.env.WEBSITE_DOMAIN_NAME} website Privacy Policy and how the user data is being processed & used.`} />
            </Head>



            <Paper m="xl" p="xl" shadow="xl" style={{ width:"75%", maxHeight:"82.75vh", margin: "0 auto", overflow:"auto" }} >


                {/* #__1__ */}
                <div style={{marginBottom:"4.5%"}} >
                    <Text style={{ fontSize:fontSizeIncrementor("xl", 1.5) }} color={$violet6} >1. Introduction</Text>
                    <pre style={{ whiteSpace:"pre-wrap", lineHeight:"3.25vh", textAlign:"justify", paddingLeft:".5%", }} >
                        1.1 We are committed to safeguarding the privacy of our website visitors, service users and individual customers.<br />
                        1.2 This policy applies where we are acting as a data controller with respect to the personal data of such persons; in other words, where we determine the purposes and means of the processing of that ou must be at least 16 years of age to use our website; by using our website or agreeing to these terms and conditions, you warrant and represent to us that you are at least 16 years of age.<br />
                    </pre>
                </div>

                
                {/* #__2__ */}
                <div style={{marginBottom:"4.5%"}} >
                    <Text style={{ fontSize:fontSizeIncrementor("xl", 1.5) }} color={$violet6} >2. Last update date</Text>
                    <pre style={{ whiteSpace:"pre-wrap", lineHeight:"3.25vh", textAlign:"justify", paddingLeft:".5%", }} >
                        2.1 This policy was last updated on 01/08/2022
                    </pre>
                </div>

                {/* #__3__ */}
                <div style={{marginBottom:"4.5%"}} >
                    <Text style={{ fontSize:fontSizeIncrementor("xl", 1.5) }} color={$violet6} >3. The personal data that we collect</Text>
                    <pre style={{ whiteSpace:"pre-wrap", lineHeight:"3.25vh", textAlign:"justify", paddingLeft:".5%", }} >
                        3.1 In this Section 3 we have set out the general categories of personal data that we process and, in the case of personal data that we did not obtain directly from you, information about the source and specific categories of that data.<br />
                        
                        3.2 We may process data enabling us to get in touch with you (&quot;contact data&quot;). The contact data may include your name and email address, The source of the contact data is you. If you log into our website using a social media account, we will obtain elements of the contact data from the relevant social media account provider.<br />
                        3.3 We may process your website user account data (&quot;account data&quot;). The account data may include your account identifier, name, email address, account creation and modification dates, website settings and marketing preferences. The primary source of the account data is you, although some elements of the account data may be generated by our website. If you log into our website using a social media account, we will obtain elements of the account data from the relevant social media account provider.<br />
                        3.4 We may process information relating to transactions, including purchases of services, that you enter into with us and/or through our website (&quot;transaction data&quot;). The transaction data may include your name, your contact details, but not your payment card details (or any other payment personal details) and the transaction details. The source of the transaction data is you and/or our payment services provider.<br />
                        3.5 We may process information contained in or relating to any communication that you send to us or that we send to you (&quot;communication data&quot;). The communication data may include the communication content and metadata associated with the communication. Our website will generate the metadata associated with communications made using the website contact forms.<br />
                        3.6 We may process data about your use of our website and services (&quot;usage data&quot;). The usage data may include your IP address, geographical location, browser type and version, operating system, referral source, length of visit, page views and website navigation paths, as well as information about the timing, frequency and pattern of your service use. The source of the usage data is our analytics tracking system.<br />
                    </pre>
                </div>

                {/* #__4__ */}
                <div style={{marginBottom:"4.5%"}} >
                    <Text style={{ fontSize:fontSizeIncrementor("xl", 1.5) }} color={$violet6} >4. Purposes of processing and legal bases</Text>
                    <pre style={{ whiteSpace:"pre-wrap", lineHeight:"3.25vh", textAlign:"justify", paddingLeft:".5%", }} >
                        4.1 In this Section 4, we have set out the purposes for which we may process personal data and the legal bases of the processing.<br />
                        
                        4.2 Operations - We may process your data for the purposes of operating our website, the processing and fulfilment of orders, providing our services, generating invoices and other payment-related documentation, and credit control. The legal basis for this processing is our legitimate interests, namely the proper administration of our website, services and business OR the performance of a contract between you and us and/or taking steps, at your request, to enter into such a contract.<br />
                        4.3 Relationships and communications - We may process contact data, account data, transaction data and/or communication data for the purposes of managing our relationships, communicating with you (excluding communicating for the purposes of direct marketing) by email, providing support services and complaint handling. The legal basis for this processing is our legitimate interests, namely communications with our website visitors, service users, individual customers and customer personnel, the maintenance of relationships, and the proper administration of our website, services and business.<br />
                        4.4 Direct marketing - We may process contact data, account data and/or transaction data for the purposes of creating, targeting and sending direct marketing communications by email for marketing-related purposes. The legal basis for this processing is consent OR our legitimate interests, namely promoting our business and communicating marketing messages and offers to our website visitors and service users.<br />
                        4.5 Research and analysis - We may process usage data and/or transaction data for the purposes of researching and analysing the use of our website and services, as well as researching and analysing other interactions with our business. The legal basis for this processing is consent OR our legitimate interests, namely monitoring, supporting, improving and securing our website, services and business generally.<br />
                        4.6 Record keeping - We may process your data for the purposes of creating and maintaining our databases, back-up copies of our databases and our records generally. The legal basis for this processing is our legitimate interests, namely ensuring that we have access to all the information we need to properly and efficiently run our business in accordance with this policy.<br />
                        4.7 Security - We may process your data for the purposes of security and the prevention of fraud and other criminal activity. The legal basis of this processing is our legitimate interests, namely the protection of our website, services and business, and the protection of others.<br />
                        4.8 Legal compliance and vital interests - We may also process your personal data where such processing is necessary for compliance with a legal obligation to which we are subject or in order to protect your vital interests or the vital interests of another natural person.<br />
                    </pre>
                </div>

                {/* #__5__ */}
                 <div style={{marginBottom:"4.5%"}} >
                    <Text style={{ fontSize:fontSizeIncrementor("xl", 1.5) }} color={$violet6} >5. Providing your personal data to others</Text>
                    <pre style={{ whiteSpace:"pre-wrap", lineHeight:"3.25vh", textAlign:"justify", paddingLeft:".5%", }} >
                        5.1 We may disclose your personal data to our professional advisers insofar as reasonably necessary for the purposes of managing risks, obtaining professional advice.<br />
                        5.2 Your data held in our website database will be stored on the servers of our hosting services providers.<br />
                        5.3 Financial transactions relating to our website and services are OR may be handled by our payment services providers, We will share transaction data with our payment services providers only to the extent necessary for the purposes of processing your payments, refunding such payments and dealing with complaints and queries relating to such payments and refunds.<br />
                        5.4 In addition to the specific disclosures of personal data set out in this Section 5, we may disclose your personal data where such disclosure is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person. We may also disclose your data where such disclosure is necessary for the establishment, exercise, or defence of legal claims.<br />
                    </pre>
                </div>

                {/* #__6__ */}
                 <div style={{marginBottom:"4.5%"}} >
                    <Text style={{ fontSize:fontSizeIncrementor("xl", 1.5) }} color={$violet6} >6. International transfers of your submited data</Text>
                    <pre style={{ whiteSpace:"pre-wrap", lineHeight:"3.25vh", textAlign:"justify", paddingLeft:".5%", }} >
                        6.1 You acknowledge that some of the data that you submit through our website may be available for some third-party services we deal with.<br />
                    </pre>
                </div>

                {/* #__7__ */}
                <div style={{marginBottom:"4.5%"}} >
                    <Text style={{ fontSize:fontSizeIncrementor("xl", 1.5) }} color={$violet6} >7. Retaining and deleting submitted data</Text>
                    <pre style={{ whiteSpace:"pre-wrap", lineHeight:"3.25vh", textAlign:"justify", paddingLeft:".5%", }} >
                        7.1 This Section 7 sets out our data retention policies and procedures, which are designed to help ensure that we comply with our legal obligations in relation to the retention and deletion of personal data.<br />
                        7.2 Personal data that we process for any purpose or purposes shall not be kept for longer than is necessary for that purpose or those purposes.<br />
                        7.3 We will retain your personal data as follows:<br />
                        (a) contact data will be retained for any period we decide following the date of the most recent contact between you and us;<br />
                        (b) account data will be retained for any period we decide following the date of closure of the relevant account;<br />
                        (c) transaction data will be retained for any period we decide following the date of the transaction;<br />
                        (d) communication data will be retained for any period we decide following the date of the communication in question;<br />
                        (e) usage data will be retained for any period we decide following the date of collection;<br />
                        
                        7.4 Notwithstanding the other provisions of this Section 7, we may retain your personal data where such retention is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.<br />
                    </pre>
                </div>

                {/* #__8__ */}
                <div style={{marginBottom:"4.5%"}} >
                    <Text style={{ fontSize:fontSizeIncrementor("xl", 1.5) }} color={$violet6} >8. Your rights</Text>
                    <pre style={{ whiteSpace:"pre-wrap", lineHeight:"3.25vh", textAlign:"justify", paddingLeft:".5%", }} >
                        8.1 In this Section 8, we have listed the rights that you have under data protection law.<br />
                        8.2 Your principal rights under data protection law are:<br />
                        (a) the right to access - you can ask for copies of your personal data;<br />
                        (b) the right to rectification - you can ask us to rectify inaccurate personal data and to complete incomplete personal data;<br />
                        (c) the right to erasure - you can ask us to erase your personal data;<br />

                        8.3 You may exercise any of your rights in relation to your personal data by noticing us, using the contact details set out on our website.<br />
                    </pre>
                </div>


                {/* #__9__ */}
                <div style={{marginBottom:"4.5%"}} >
                    <Text style={{ fontSize:fontSizeIncrementor("xl", 1.5) }} color={$violet6} >9. About cookies</Text>
                    <pre style={{ whiteSpace:"pre-wrap", lineHeight:"3.25vh", textAlign:"justify", paddingLeft:".5%", }} >
                        9.1 A cookie is a file containing an identifier (a string of letters and numbers) that is sent by a web server to a web browser and stored by the browser. The identifier is then sent back to the server each time the browser requests a page from the server.<br />
                        9.2 Cookies may be either &quot;persistent&quot; cookies or &quot;session&quot; cookies: a persistent cookie will be stored by a web browser and will remain valid until its set expiry date, unless deleted by the user before the expiry date; a session cookie, on the other hand, will expire at the end of the user session, when the web browser is closed.<br />
                        9.3 Cookies may not contain any information that personally identifies a user, but the data that we store about you may be linked to the information stored in and obtained from cookies.<br />
                    </pre>
                </div>

                {/* #__10__ */}
                <div style={{marginBottom:"4.5%"}} >
                    <Text style={{ fontSize:fontSizeIncrementor("xl", 1.5) }} color={$violet6} >10. Cookies that we use</Text>
                    <pre style={{ whiteSpace:"pre-wrap", lineHeight:"3.25vh", textAlign:"justify", paddingLeft:".5%", }} >
                        10.1 We use cookies for the following purposes:<br />
                        (a) authentication and status - we use cookies to identify you when you visit our website and as you navigate our website, and to help us determine if you are logged into our website;<br />
                        (b) personalisation - we use cookies to store information about your preferences;<br />
                        (c) security - we use cookies as an element of the security measures used to protect user accounts, including preventing fraudulent use of login credentials, and to protect our website and services generally;<br />
                        (d) analysis - we use cookies to help us to analyse the use and performance of our website and services; and<br />
                        (e) cookie consent - we use cookies to store your preferences in relation to the use of cookies more generally.<br />
                    </pre>
                </div>

                {/* #__11__ */}
                <div style={{marginBottom:"4.5%"}} >
                    <Text style={{ fontSize:fontSizeIncrementor("xl", 1.5) }} color={$violet6} >11. Cookies used by our service providers</Text>
                    <pre style={{ whiteSpace:"pre-wrap", lineHeight:"3.25vh", textAlign:"justify", paddingLeft:".5%", }} >
                        11.1 Our service providers use cookies and those cookies may be stored on your computer when you visit our website.<br />
                        11.2 We may use Google Analytics. Google Analytics gathers information about the use of our website by means of cookies. The information gathered is used to create reports about the use of our website. You can find out more about Google's use of information by visiting https://www.google.com/policies/privacy/partners/ and you can review Google's privacy policy at https://policies.google.com/privacy.<br />
                        11.3 We also may use other services to help us offer you the best of us which may be using cookies as well.<br />
                    </pre>
                </div>

                {/* #__12__ */}
                <div style={{marginBottom:"4.5%"}} >
                    <Text style={{ fontSize:fontSizeIncrementor("xl", 1.5) }} color={$violet6} >12. Managing cookies</Text>
                    <pre style={{ whiteSpace:"pre-wrap", lineHeight:"3.25vh", textAlign:"justify", paddingLeft:".5%", }} >
                        12.1 Most browsers allow you to refuse to accept cookies and to delete cookies. The methods for doing so vary from browser to browser, and from version to version. You can however obtain up-to-date information about blocking and deleting cookies via these links:<br />
                        (a) https://support.google.com/chrome/answer/95647 (Chrome);<br />
                        (b) https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop (Firefox);<br />
                        (c) https://help.opera.com/en/latest/security-and-privacy/ (Opera);<br />
                        (d) https://support.apple.com/en-gb/guide/safari/manage-cookies-and-website-data-sfri11471/mac (Safari); and<br />
                        (e) https://support.microsoft.com/en-gb/help/4468242/microsoft-edge-browsing-data-and-privacy (Edge).<br />
                        
                        12.2 Blocking all cookies will have a negative impact upon the usability of many websites.<br />
                        12.3 If you block cookies, you may not be able to use the core features on our website and hence may not be able to get a use out of the services we offer.<br />
                    </pre>
                </div>

                {/* #__13__ */}
                <div style={{marginBottom:"4.5%"}} >
                    <Text style={{ fontSize:fontSizeIncrementor("xl", 1.5) }} color={$violet6} >13. Amendments</Text>
                    <pre style={{ whiteSpace:"pre-wrap", lineHeight:"3.25vh", textAlign:"justify", paddingLeft:".5%", }} >
                        13.1 We may update this policy from time to time by publishing a new version on our website.<br />
                        13.2 You should check this page occasionally to ensure you are happy with any changes to this policy.<br />
                        13.3 We may OR will notify you of changes OR significant changes to this policy by email.
                    </pre>
                </div>

                

            </Paper>

        </Fragment>
    );
}


export default PrivacyPolicy;